In [1]:
%gui qt
from importlib import reload
import xanes_regtools_gui as xrg
xrg = reload(xrg)
gui = xrg.xanes_regtools_gui(form_sz=[750, 1000])
gui.gui_layout()


/home/xiao/software/anaconda3/envs/py37play/lib/python3.7/site-packages/napari/__init__.py:44: UserWarning: 
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.6. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.
    
  warn(message=warn_message)
/home/xiao/software/anaconda3/envs/py37play/lib/python3.7/site-packages/vispy/visuals/line/line.py:395: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('color', np.float32, 4)])
/home/xiao/software/anaconda3/envs/py37play/lib/python3.7/site-packages/vispy/visuals/line/arrow.py:57: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('linewidth', np.float32, 1)
/home/xiao/software/anaconda3/envs/py37play/lib/python3.7/site-packages/visp

Added 390 JARs to the Java classpath.
fiji is already up running!


In [3]:
%matplotlib qt
import matplotlib.pyplot as plt
import numpy as np
#help(plt.plot)
x, y= [], []
for i, j in gui.xanes3D_review_shift_dict.items():
    x.append(int(i))
    #print(i, j)
    y.append(j[0])
#print(sorted(x))
#print(len(x))
plt.plot(x, y, 'b+', scalex=True)
plt.grid(which='both', snap=True)
plt.xticks(np.arange(0, 101, 5))
#print(gui.xanes3D_review_shift_dict)

([<matplotlib.axis.XTick at 0x7f5f08938588>,
 <a list of 21 Text major ticklabel objects>)

In [2]:
print(gui.xanes3D_roi)

[434, 817, 118, 1158, 430, 530]


In [65]:
import napari, h5py
fn = '/NSLS2/xf18id1/users/2020Q1/ENYUAN_Proposal_305409/3D_trial_reg_scan_id_29671-29771_2020-05-28-17-54-45.h5'
f = h5py.File(fn, 'r')
#img = f['/processed_XANES3D/proc_spectrum/spectrum_whiteline_pos'][:]
#img = f['/registration_results/reg_results/registered_xanes3D'][:, 0, :, :]
#viewer = napari.view_image(img)
#spec = f['/processed_XANES3D/proc_spectrum/spectrum_whiteline_pos'][1, :]
#spec = f['/processed_XANES3D/proc_spectrum/spectrum_edge0.5_pos'][:]
#spec = f['/processed_XANES3D/proc_spectrum/specturm_edge_jump_filter'][:]
spec = f['/processed_XANES3D/proc_spectrum/specturm_edge_offset_filter'][:]
viewer = napari.view_image(spec)
f.close()

In [ ]:
flt_param_dict = gui.tomo_recon_gui.tomo_recon_param_dict['flt_params']['filters']
for idx in sorted(flt_param_dict.keys()):
    print(idx)
    flt = flt_param_dict[idx]
    print(flt)
    flt_name = list(flt.keys())[0]
    print(flt_name)
    print(flt[flt_name])

In [8]:
dir(gui.xanes3D_fiji_windows['xanes3D_review_viewer']['ip'])
#help(gui.xanes3D_fiji_windows['xanes3D_review_viewer']['ip'].getStackIndex())

['ABORT',
 'ADD_TO_OVERLAY',
 'ALLBITS',
 'ALL_STATS',
 'AREA',
 'AREA_FRACTION',
 'CENTER_OF_MASS',
 'CENTROID',
 'CIRCULARITY',
 'COLOR_256',
 'COLOR_RGB',
 'ELLIPSE',
 'ERROR',
 'FERET',
 'FRAMEBITS',
 'GRAY16',
 'GRAY32',
 'GRAY8',
 'HEIGHT',
 'INTEGRATED_DENSITY',
 'INVERT_Y',
 'KURTOSIS',
 'LABELS',
 'LIMIT',
 'MAX_STANDARDS',
 'MEAN',
 'MEDIAN',
 'MIN_MAX',
 'MODE',
 'NaN_EMPTY_CELLS',
 'PERIMETER',
 'PROPERTIES',
 'RECT',
 'SCIENTIFIC_NOTATION',
 'SHAPE_DESCRIPTORS',
 'SKEWNESS',
 'SLICE',
 'SOMEBITS',
 'STACK_POSITION',
 'STD_DEV',
 'WIDTH',
 '__class__',
 '__cls_storage',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__javaclass__',
 '__javaconstructor__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__pyx_vtable__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclassho

In [1]:
import numpy as np
import imagej
import time

ij = imagej.init('/home/xiao/software/Fiji.app', headless=False)
ijui = ij.ui()
ijui.showUI()

In [61]:
import h5py
fn = '/NSLS2/xf18id1/users/2020Q1/ENYUAN_Proposal_305409/3D_trial_reg_scan_id_29671-29771_2020-05-28-17-54-45.h5'
f = h5py.File(fn, 'a')
img = f['/registration_results/reg_results/registered_xanes3D'][50, :]
fit = f['/processed_XANES3D/proc_spectrum/spectrum_whiteline_pos'][:]
f.close()

In [55]:
from jnius import autoclass
WindowManager = autoclass('ij.WindowManager')
ImagePlusClass = autoclass('ij.ImagePlus')

ijui.show(ij.py.to_java(img))
img_win = WindowManager.getCurrentWindow()
WindowManager.setCurrentWindow(img_win)

In [56]:
ij.py.run_macro("""run("Duplicate...", "title=VOL duplicate");""")

ll=0.0015
hl = 1
ij.py.run_macro(f"""setThreshold({ll}, {hl});""")
ij.py.run_macro("""run("Convert to Mask", "method=Default background=Dark black");""")
mask_win = WindowManager.getCurrentWindow()

In [57]:
WindowManager.setCurrentWindow(mask_win)
ij.py.run_macro("""run("Remove Outliers", "block_radius_x=100 block_radius_y=100 standard_deviations=3 stack");""")

for ii in range(3):
    ij.py.run_macro("""run("Erode (3D)", "iso=255");""")
for ii in range(8):
    ij.py.run_macro("""run("Dilate (3D)", "iso=255");""")
for ii in range(3):
    ij.py.run_macro("""run("Erode (3D)", "iso=255");""")

In [62]:
WindowManager.setCurrentWindow(mask_win)
mask_ip = WindowManager.getCurrentImage()
mask1 = ij.py.from_java(mask_ip)
fit *= (mask1/255.)
ijui.show(ij.py.to_java(fit))
ij.py.run_macro("""call("java.lang.System.gc");""")

<org.scijava.script.ScriptModule at 0x7f91b434ee60 jclass=org/scijava/script/ScriptModule jself=<LocalRef obj=0x5600d87fbf68 at 0x7f91cfdbf930>>

<org.scijava.script.ScriptModule at 0x7f91cfdc7780 jclass=org/scijava/script/ScriptModule jself=<LocalRef obj=0x7f90f82d7148 at 0x7f91b4358bb0>>

In [66]:
np.array([True, False]).astype(np.int8)

array([1, 0], dtype=int8)

In [2]:
gui.a = 0

In [4]:
print(gui.a)

0


In [1]:
%gui qt
from importlib import reload
import xanes_regtools_gui_develop as xrg
#xrg = reload(xrg)
gui = xrg.xanes_regtools_gui(form_sz=[750, 1000])
gui.gui_layout()

/home/xiao/software/anaconda3/envs/py37play/lib/python3.7/site-packages/napari/__init__.py:44: UserWarning: 
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.6. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.
    
  warn(message=warn_message)
/home/xiao/software/anaconda3/envs/py37play/lib/python3.7/site-packages/vispy/visuals/line/line.py:395: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('color', np.float32, 4)])
/home/xiao/software/anaconda3/envs/py37play/lib/python3.7/site-packages/vispy/visuals/line/arrow.py:57: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('linewidth', np.float32, 1)
/home/xiao/software/anaconda3/envs/py37play/lib/python3.7/site-packages/visp

Added 390 JARs to the Java classpath.


In [35]:
#dir(gui.tomo_fiji_windows['tomo_cen_review_viewer']['ip'])
#a = gui.ij.py.run_macro("""run("Show Info...")""")
#dir(gui.WindowManager)
#gui.WindowManager.getFrame(1)
gui.tomo_fiji_windows['tomo_cen_review_viewer']['ip'].getZ()

21

In [6]:
print(a[0])

TypeError: 'org.scijava.script.ScriptModule' object is not subscriptable

In [2]:
import ipywidgets as widgets

widgets.Textarea(
    value='Hello World\nsecond line',
    placeholder='Type something',
    description='String:',
    disabled=False
)

a = set()
print(a)
for ii in [1,2,3,1]:
    a.add(ii)
print(a)
a.remove(1)
print(a)

set()
{1, 2, 3}
{2, 3}


In [19]:
import xanes_analysis as xa, h5py
fn = '/media/xiao_usb/JuLi_2020Q1/2D_trial_reg_xanes_scan2_id_54312_2020-07-03-21-00-36.h5'
with h5py.File(fn, 'r') as f:
    normalized_spectrum = f['/processed_XANES2D/proc_spectrum/normalized_spectrum'][:]
    eng_list = f['/processed_XANES2D/proc_parameters/eng_list'][:]
xana = xa.xanes_analysis(normalized_spectrum, eng_list, 8347, pre_ee=-50, post_es=100, edge_jump_threshold=1, pre_edge_threshold=1)
xana.normalized_spectrum = normalized_spectrum
#xana.fit_edge(8342, 8353, 'numpy', **{'order': 3, 'ufac': 50, 'flt_spec': False})
xana.fit_edge_0p5(8342, 8353, 'numpy', **{'order': 3, 'ufac': 50, 'flt_spec': False})
xana.calc_edge_0p5_direct(8342, 8353)

fit_edge_poly
fit_polynd is done
find_fit_edge_0p5_map_poly is done
Something wrong in find_fit_edge_0p5_map_poly


In [62]:
import numpy as np
print(normalized_spectrum.max(), normalized_spectrum.min())
a = np.argmin(np.abs(normalized_spectrum-0.5), axis=0)
print('a:', a.shape)
idx = np.unravel_index(a.flatten(), normalized_spectrum.shape)
print('idx len:', len(idx), '\nidx shape:', idx[1].shape)
print(101*1784*2082)
b = normalized_spectrum[idx].reshape(normalized_spectrum.shape[1:])
c = normalized_spectrum.flatten()[a.flatten()].reshape(normalized_spectrum.shape[1:])
print('normalized_spectrum.shape:', normalized_spectrum.shape, 
      '\na shape:', a.shape, 
      '\nb shape:', b.shape,
      '\nc shape:', c.shape)

602995.0 -1194570.0
a: (1784, 2082)
idx len: 3 
idx shape: (3714288,)
375143088
normalized_spectrum.shape: (101, 1784, 2082) 
a shape: (1784, 2082) 
b shape: (1784, 2082) 
c shape: (1784, 2082)


In [86]:
eng = np.linspace(1, 21, 21)
eng = eng[:, np.newaxis, np.newaxis]
a = np.random.randint(low=0, high=20, size=(3, 4))
print(np.squeeze(eng), '\n', a)
print('eng shape:', eng.shape, '\na shape:', a.shape)
print(eng[a].shape)
print(np.squeeze(eng[a]))
#ind = np.unravel_index(np.argmin(a, axis=0), a.shape)
#print(np.argmin(a, axis=0))
#print(ind)
#print(a[ind])

'''
ax = -1
ind = np.argmin(a, axis=ax)
c = np.take_along_axis(a, np.expand_dims(ind, axis=ax), axis=ax)
print(ind)
print(c)
'''

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21.] 
 [[ 4 12 14 13]
 [ 1  8  0 10]
 [15 10 12  8]]
eng shape: (21, 1, 1) 
a shape: (3, 4)
(3, 4, 1, 1)
[[ 5. 13. 15. 14.]
 [ 2.  9.  1. 11.]
 [16. 11. 13.  9.]]


'\nax = -1\nind = np.argmin(a, axis=ax)\nc = np.take_along_axis(a, np.expand_dims(ind, axis=ax), axis=ax)\nprint(ind)\nprint(c)\n'

In [3]:
#help(np.random.randint)
if ('a' or 'b') in 'kcg':
    print('yes')
else:
    print('no')

no


In [63]:
%matplotlib qt
import matplotlib.pyplot as plt
#plt.imshow(xana.edge_pos_fit)
#plt.plot(xana.edge_pos_fit)
#plt.plot(xana.edge_pos_0p5_direct)
#print(xana.edge_pos_0p5_direct)
#gui.ijui.show(gui.ij.py.to_java(xana.edge_pos_0p5_direct))
plt.figure(0)
plt.imshow(b)
plt.figure(1)
plt.imshow(c)
plt.figure(2)
plt.imshow(b-c)

In [8]:
#print((gui.xanes2D_gui.hs['L[0][1][2][0][2][0]_reg_pair_slider'].max))
#print((gui.xanes2D_gui.xanes2D_reg_roi))
#gui.xanes2D_gui.xanes_analysis_gui_h.hs['L[0][x][3][0][5][1]_analysis_run_button'].disabled = False
#print(1300*1960*2360*8/1024/1024/1024)
#gui.xanes2D_gui.xanes_analysis_gui_h.
#print(gui.xanes3D_gui.xanes3D_config['indeices config']['xanes3D_scan_id_s'])
#print(gui.xanes3D_gui.xanes3D_config)
print(gui.xanes3D_gui.xanes3D_fixed_scan_id)

56605


In [2]:
import numpy as np
from gui_components import (SelectFilesButton, NumpyArrayEncoder, 
                            get_handles, enable_disable_boxes, 
                            check_file_availability, get_raw_img_info,
                            gen_external_py_script, fiji_viewer_state, 
                            fiji_viewer_on, fiji_viewer_off,
                            read_config_from_reg_file, restart,
                            determine_element, determine_fitting_energy_range,
                            scale_eng_list)
#gui.xanes2D_gui.xanes_analysis_gui_h.normalized_spectrum
#fiji_viewer_on(gui, gui.xanes2D_gui, viewer_name='xanes2D_raw_img_viewer')
boxes = ['L[0][1][0][1]_config_data_box']
enable_disable_boxes(gui.xanes2D_gui.hs, boxes, disabled=True, level=-1)

In [1]:
import os, h5py
import numpy as np
import xanes_math as xm
import xanes_analysis as xa

with h5py.File('/media/xiao_usb/JuLi_2020Q1/2D_trial_reg_xanes_scan2_id_54311_2020-07-01-11-20-34.h5', 'r+') as f:
    imgs = f['/registration_results/reg_results/registered_xanes2D'][:]
    xanes2D_analysis_eng_list = f['/processed_XANES2D/proc_parameters/eng_list'][:]
    xanes2D_analysis_edge_eng = f['/processed_XANES2D/proc_parameters/edge_eng'][()]
    xanes2D_analysis_pre_edge_e = f['/processed_XANES2D/proc_parameters/pre_edge_e'][()]
    xanes2D_analysis_post_edge_s = f['/processed_XANES2D/proc_parameters/post_edge_s'][()]
    xanes2D_analysis_edge_jump_thres = f['/processed_XANES2D/proc_parameters/edge_jump_threshold'][()]
    xanes2D_analysis_edge_offset_thres = f['/processed_XANES2D/proc_parameters/edge_offset_threshold'][()]
    xanes2D_analysis_use_mask = f['/processed_XANES2D/proc_parameters/use_mask'][()]
    xanes2D_analysis_type = f['/processed_XANES2D/proc_parameters/analysis_type'][()]
    xanes2D_analysis_data_shape = f['/processed_XANES2D/proc_parameters/data_shape'][:]
    xanes2D_analysis_data_shape = imgs.shape
    xanes2D_analysis_edge_0p5_fit_s = f['/processed_XANES2D/proc_parameters/edge_0p5_fit_s'][()]
    xanes2D_analysis_edge_0p5_fit_e = f['/processed_XANES2D/proc_parameters/edge_0p5_fit_e'][()]
    xanes2D_analysis_wl_fit_eng_s = f['/processed_XANES2D/proc_parameters/wl_fit_eng_s'][()]
    xanes2D_analysis_wl_fit_eng_e = f['/processed_XANES2D/proc_parameters/wl_fit_eng_e'][()]
    xanes2D_analysis_use_flt_spec = f['/processed_XANES2D/proc_parameters/flt_spec'][()]
    xanes2D_analysis_norm_fitting_order = f['/processed_XANES2D/proc_parameters/normalized_fitting_order'][()]
    xana = xa.xanes_analysis(imgs, xanes2D_analysis_eng_list, xanes2D_analysis_edge_eng, pre_ee=xanes2D_analysis_pre_edge_e, post_es=xanes2D_analysis_post_edge_s, edge_jump_threshold=xanes2D_analysis_edge_jump_thres, pre_edge_threshold=xanes2D_analysis_edge_offset_thres)


    if xanes2D_analysis_type == 'wl':
        xana.fit_whiteline(xanes2D_analysis_wl_fit_eng_s, xanes2D_analysis_wl_fit_eng_e, 'numpy', **{'order': 3, 'ufac': 50, 'flt_spec': False})
        if True:
            xana.fit_edge(xanes2D_analysis_edge_0p5_fit_s, xanes2D_analysis_edge_0p5_fit_e, 'numpy', **{'order': 4, 'ufac': 50, 'flt_spec': False})
        xana.calc_direct_whiteline(xanes2D_analysis_wl_fit_eng_s, xanes2D_analysis_wl_fit_eng_e)
    elif xanes2D_analysis_type == 'full':
        xana.fit_pre_edge()
        xana.fit_post_edge()
        xana.cal_edge_jump_map()
        xana.cal_pre_edge_sd()
        xana.cal_post_edge_sd()
        xana.cal_pre_edge_mean()
        xana.cal_post_edge_mean()
        xana.create_edge_jump_filter(xanes2D_analysis_edge_jump_thres)
        xana.create_fitted_edge_filter(xanes2D_analysis_edge_offset_thres)
        xana.normalize_xanes(xanes2D_analysis_edge_eng, order=xanes2D_analysis_norm_fitting_order, save_pre_post=True)
        xana.fit_whiteline(xanes2D_analysis_wl_fit_eng_s, xanes2D_analysis_wl_fit_eng_e, 'numpy', **{'order': 3, 'ufac': 50, 'flt_spec': False})
        if True:
            xana.fit_edge(xanes2D_analysis_edge_0p5_fit_s, xanes2D_analysis_edge_0p5_fit_e, 'numpy', **{'order': 4, 'ufac': 50, 'flt_spec': False})
        xana.calc_direct_whiteline(xanes2D_analysis_wl_fit_eng_s, xanes2D_analysis_wl_fit_eng_e)
        xana.calc_direct_whiteline_peak_height(xanes2D_analysis_wl_fit_eng_s, xanes2D_analysis_wl_fit_eng_e)
        xana.calc_weighted_eng(xanes2D_analysis_pre_edge_e)
        


[numexpr.utils] INFO : Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[numexpr.utils] INFO : NumExpr defaulting to 8 threads.
[dxchange.reader] WARNING : astropy module not found


pre_es_idx: 0, pre_ee_idx: 8
post_es_idx: 92, post_ee_idx: 100
(2, 1960, 2360) (2, 1960, 2360)
(2, 1960, 2360)
(2, 1960, 2360)
(2, 1960, 2360)
(2, 1960, 2360)
(2, 1960, 2360)
(2, 1960, 2360)
(2, 1960, 2360)
(2, 1960, 2360)


In [18]:
xanes3D_analysis_data_shape = imgs.shape
print(xanes3D_analysis_data_shape)
xanes3D_analysis_data_shape = xanes3D_analysis_data_shape[:, np.newaxis, :]
print(xanes3D_analysis_data_shape)

(10, 50, 50)


TypeError: tuple indices must be integers or slices, not tuple

In [47]:
from copy import deepcopy

#print(xana.wl_fit_coef.shape)
eng = deepcopy(xana.eng)
peak_es = 7722
peak_ee = 7735
ufac = 10
idx_s = xm.index_of(xana.eng, peak_es)
idx_e = xm.index_of(xana.eng, peak_ee)
us_idx = np.linspace(idx_s, idx_e, num=(idx_e - idx_s + 1)*ufac)
for ii in range(1, len(xana.wl_fit_coef.shape)):
    us_idx = us_idx[:, np.newaxis] 
    eng = eng[:, np.newaxis]
    
wl = xm.find_fit_peak_map_poly(xana.wl_fit_coef, us_idx)

#wlp = xm.index_lookup(wl, eng, ufac=ufac)

print('eng:', eng.shape)
print('idx_ds:', idx_ds.shape)
idx_ds = wl
x = np.squeeze(eng[np.int_(np.floor(idx_ds))]) + \
    np.squeeze(eng[np.int_(np.ceil(idx_ds))]-eng[np.int_(np.floor(idx_ds))])*\
    np.squeeze(idx_ds - np.floor(idx_ds))/np.squeeze(np.ceil(idx_ds) - np.floor(idx_ds))
print('x:', x.shape)
plt.imshow(x)
ijui.show(ij.py.to_java(x))

y = np.squeeze(eng[np.int_(np.floor(idx_ds))])
print('y:', y.shape)


z = np.squeeze(eng[np.int_(np.ceil(idx_ds))]-eng[np.int_(np.floor(idx_ds))])
print('z:', z.shape)


z1 = (idx_ds - np.floor(idx_ds))
print('z1:', z1.shape)


z2 = (np.ceil(idx_ds) - np.floor(idx_ds))
print('z2:', z2.shape)

#print(wlp.shape)
#plt.imshow(wlp)

#e0p5 = xm.find_fit_edge_0p5_map_poly(xana.wl_fit_coef, us_idx)
#print(e0p5.shape)
#plt.imshow(e0p5)

#ep = xm.find_deriv_peak_map_poly(xana.wl_fit_coef, us_idx)
#print(ep.shape)
#plt.imshow(ep)

#print(us_idx)
print(xana.eng[int(us_idx[0])])
"""
print(xana.wl_pos.shape)
print(xana.edge_pos.shape)
print(xana.edge_pos_0p5.shape)
"""

eng: (101, 1, 1)
idx_ds: (100, 100)
x: (100, 100)
y: (100, 100)
z: (100, 100)
z1: (100, 100)
z2: (100, 100)
7722.0


'\nprint(xana.wl_pos.shape)\nprint(xana.edge_pos.shape)\nprint(xana.edge_pos_0p5.shape)\n'

In [16]:
print(xana.edge_pos.shape)
print(xana.edge_pos_0p5.max(), xana.edge_pos_0p5.min())
#plt.imshow(xana.edge_pos_0p5)
plt.imshow(wl)

(10000,)
7594.6 7593.3


In [4]:
import xanes_math as xm
xm.index_of(xana.eng, 7730)

51

In [14]:
%matplotlib qt
import matplotlib.pyplot as plt
import imagej
ij = imagej.init('/home/xiao/software/Fiji.app', headless=False)
ijui = ij.ui()
ijui.showUI()
#from jnius import autoclass
#wm = autoclass('ij.WindowManager')


ValueError: VM is already running, can't set classpath

In [9]:
from lmfit.lineshapes import (gaussian, lorentzian, voigt, pvoigt, moffat, pearson7,
                         breit_wigner, damped_oscillator, dho, logistic, lognormal,
                         students_t, expgaussian, donaich, skewed_gaussian,
                         skewed_voigt, step, rectangle,  
                         exponential, powerlaw, linear, parabolic, sine, 
                         expsine, split_lorentzian)

functions = {'gaussian':gaussian, 'lorentzian':lorentzian, 'voigt':voigt, 
             'pvoigt':pvoigt, 'moffat':moffat, 'pearson7':pearson7,
             'breit_wigner':breit_wigner, 'damped_oscillator':damped_oscillator,
             'dho':dho, 'logistic':logistic, 'lognormal':lognormal,
             'students_t':students_t, 'expgaussian':expgaussian, 
             'donaich':donaich, 'skewed_gaussian':skewed_gaussian,
             'skewed_voigt':skewed_voigt, 'step':step, 'rectangle':rectangle, 
             'exponential':exponential, 'powerlaw':powerlaw, 
             'linear':linear, 'parabolic':parabolic, 'sine':sine, 
             'expsine':expsine, 'split_lorentzian':split_lorentzian}

In [24]:
#ln = np.ployval(xana.pre_edge_fit_coef[:, 55, 65], xana.eng)
pre_edge = xana.cal_pre_edge_fit(xana.eng)
post_edge = xana.cal_post_edge_fit(xana.eng)
print(pre_edge.shape, post_edge.shape)
print(xana.wl_fit_coef.shape)
print(xanes2D_analysis_wl_fit_eng_s)
func = functions['lorentzian']
rn = 100
rs = 50
re = 52
cs = 80
ce = 82
plt.figure(1)
for ii in range(rs, re):
    for jj in range(cs, ce):
        idx = ii*rn+jj
        plt.plot(np.linspace(xanes2D_analysis_wl_fit_eng_s, xanes2D_analysis_wl_fit_eng_e, 100),
                 func(np.linspace(xanes2D_analysis_wl_fit_eng_s, xanes2D_analysis_wl_fit_eng_e, 100), 
                 xana.wl_fit_coef[idx, 0], 
                 xana.wl_fit_coef[idx, 1], 
                 xana.wl_fit_coef[idx, 2]))

plt.figure(2)
for ii in range(rs, re):
    for jj in range(cs, ce):
        idx = ii*rn+jj
        plt.plot(xana.eng, xana.normalized_spectrum[:, ii, jj])
        
plt.figure(3)
for ii in range(rs, re):
    for jj in range(cs, ce):
        idx = ii*rn+jj
        plt.plot(xana.eng, xana.spectrum[:, ii, jj])
        plt.plot(xana.eng, pre_edge[:, ii, jj])
        plt.plot(xana.eng, post_edge[:, ii, jj])

(101, 100, 100) (101, 100, 100)
(10000, 3)
7722.0


In [18]:
xana.fit_whiteline_poly(7722, 7735, order=3, ufac=10, flt_spec=False)
print(xana.spec_normalized)
idx_s = xm.index_of(xana.eng, 7722)
idx_e = xm.index_of(xana.eng, 7735)
print(idx_s, idx_e)
wlc = xm.fit_polynd(np.arange(0, idx_e-idx_s), xana.normalized_spectrum[idx_s:idx_e, :], 3)
print(wlc.shape)

print(wlc[:, 50, 50])

plt.plot(xana.eng[idx_s:idx_e], np.polyval(wlc[:, 50, 50], np.arange(0, idx_e-idx_s)))

#plt.plot(xm.find_fit_peak_map_poly(xana.wl_fit_coef[], xana.eng[:, np.newaxis, np.newaxis]))
print(xana.wl_fit_coef.shape)
print(xana.wl_es, xana.wl_ee)
rn = 100
rs = 50
re = 52
cs = 80
ce = 82
plt.figure(1)
for ii in range(rs, re):
    for jj in range(cs, ce):
        idx = ii*rn+jj
        print(xana.wl_fit_coef[:, ii, jj])
        a = np.polyval(xana.wl_fit_coef[:, ii, jj], np.arange(idx_s, idx_e))
        print(a.shape)
        plt.plot(xana.eng[idx_s:idx_e], a)
print(xana.eng)


True
43 56
(4, 100, 100)
[-0.00321435  0.01884423  0.36112244  0.22727432]
(4, 100, 100)
7722.0 7735.0
[-2.01827005e-03  2.69433145e-01 -1.17351729e+01  1.67436791e+02]
(13,)
[-2.90381798e-03  3.94281819e-01 -1.75506642e+01  2.56893541e+02]
(13,)
[-2.81801596e-03  3.86285359e-01 -1.73955239e+01  2.58302138e+02]
(13,)
[-3.55168156e-03  4.93474959e-01 -2.25992041e+01  3.42210810e+02]
(13,)
[7589. 7599. 7609. 7619. 7629. 7639. 7649. 7659. 7669. 7679. 7689. 7690.
 7691. 7692. 7693. 7694. 7695. 7696. 7697. 7698. 7699. 7700. 7701. 7702.
 7703. 7704. 7705. 7706. 7707. 7708. 7709. 7710. 7711. 7712. 7713. 7714.
 7715. 7716. 7717. 7718. 7719. 7720. 7721. 7722. 7723. 7724. 7725. 7726.
 7727. 7728. 7729. 7730. 7731. 7732. 7733. 7734. 7735. 7736. 7737. 7738.
 7739. 7740. 7741. 7742. 7743. 7744. 7745. 7746. 7747. 7748. 7749. 7750.
 7751. 7752. 7753. 7754. 7755. 7756. 7757. 7758. 7759. 7760. 7761. 7762.
 7763. 7764. 7765. 7766. 7767. 7768. 7769. 7794. 7834. 7874. 7914. 7954.
 7994. 8034. 8074. 8114. 

In [6]:
ijui.show(ij.py.to_java(xana.wl_pos))
p = wm.getCurrentImage()
p.setTitle('wl_pos')
ijui.show(ij.py.to_java(xana.edge_pos))
p = wm.getCurrentImage()
p.setTitle('edge_pos')
ijui.show(ij.py.to_java(xana.edge_pos_0p5))
p = wm.getCurrentImage()
p.setTitle('edge_pos_0p5')

"""
%matplotlib qt
import matplotlib.pyplot as plt

plt.figure(1)
plt.imshow(xana.wl_pos, vmin=7729, vmax=7731)
plt.figure(2)
plt.imshow(xana.edge_pos, vmin=7723, vmax=7725)
plt.figure(3)
plt.imshow(xana.edge_pos_0p5, vmin=7727, vmax=7729)
"""

'\n%matplotlib qt\nimport matplotlib.pyplot as plt\n\nplt.figure(1)\nplt.imshow(xana.wl_pos, vmin=7729, vmax=7731)\nplt.figure(2)\nplt.imshow(xana.edge_pos, vmin=7723, vmax=7725)\nplt.figure(3)\nplt.imshow(xana.edge_pos_0p5, vmin=7727, vmax=7729)\n'

In [4]:
print(xanes2D_analysis_norm_fitting_order)
print('pre_edge_fit', xana.pre_edge_fit.shape)
print('xana.wl_pos', xana.wl_pos.shape)
print('xana.wl_pos_direct', xana.wl_pos_direct.shape)
print('xana.direct_wl_ph', xana.direct_wl_ph.shape)
print('xana.centroid_of_eng', xana.centroid_of_eng.shape)
print('xana.centroid_of_eng_rel_wl', xana.centroid_of_eng_rel_wl.shape)
print('xana.weighted_atten', xana.weighted_atten.shape)
print('xana.weighted_eng', xana.weighted_eng.shape)
print('xana.edge_pos_0p5', xana.edge_pos_0p5.shape)
print('xana.edge_pos', xana.edge_pos.shape)
print('xana.edge_jump_mask', xana.edge_jump_mask.shape)
print('xana.fitted_edge_mask', xana.fitted_edge_mask.shape)
print('xana.pre_edge_sd_map', xana.pre_edge_sd_map.shape)
print('xana.post_edge_sd_map', xana.post_edge_sd_map.shape)
print('xana.pre_edge_mean_map', xana.pre_edge_mean_map.shape)
print('xana.post_edge_mean_map', xana.post_edge_mean_map.shape)
print('xana.pre_edge_fit_coef', xana.pre_edge_fit_coef.shape)
print('xana.post_edge_fit_coef', xana.post_edge_fit_coef.shape)
print('edge_fit_coef',xana.edge_fit_coef.shape)
print('xana.wl_fit_coef', xana.wl_fit_coef.shape)


1


AttributeError: 'NoneType' object has no attribute 'shape'

In [2]:
import numpy as np
for ii in gui.xanes3D_gui.xanes_analysis_gui_h.ana_edge_optimizer_arg_handles:
    ii.disabled = True
    #print(ii)
for ii in gui.xanes3D_gui.xanes_analysis_gui_h.ana_edge_fit_func_arg_handles:
    ii.disabled = True
    #print(ii)
help(np.gradient)

Help on function gradient in module numpy:

gradient(f, *varargs, **kwargs)
    Return the gradient of an N-dimensional array.
    
    The gradient is computed using second order accurate central differences
    in the interior points and either first or second order accurate one-sides
    (forward or backwards) differences at the boundaries.
    The returned gradient hence has the same shape as the input array.
    
    Parameters
    ----------
    f : array_like
        An N-dimensional array containing samples of a scalar function.
    varargs : list of scalar or array, optional
        Spacing between f values. Default unitary spacing for all dimensions.
        Spacing can be specified using:
    
        1. single scalar to specify a sample distance for all dimensions.
        2. N scalars to specify a constant sample distance for each dimension.
           i.e. `dx`, `dy`, `dz`, ...
        3. N arrays to specify the coordinates of the values along each
           dimension of

In [7]:
from gui_components import enable_disable_boxes, get_decendant
boxes = ['L[0][x][3][0][4][0]_ana_fit_wl_param_box',
                 'L[0][x][3][0][4][2]_ana_fit_edge_param_box',
                 'L[0][x][3][0][4][1]_ana_save_setting_box']
enable_disable_boxes(gui.xanes2D_gui.xanes_analysis_gui_h.hs, boxes, disabled=False, level=-1)
#enable_disable_boxes(gui.xanes3D_gui.xanes_analysis_gui_h.hs, ['L[0][x][3][0][4][0][0]'], disabled=False, level=-1)
#enable_disable_boxes(gui.xanes3D_gui.xanes_analysis_gui_h.hs, ['L[0][x][3][0][4][1][0]'], disabled=False, level=-1)
#enable_disable_boxes(gui.xanes3D_gui.xanes_analysis_gui_h.hs, ['L[0][x][3][0][4][2][0]'], disabled=False, level=-1)
#print(get_decendant(gui.xanes3D_gui.xanes_analysis_gui_h.hs, 'L[0][x][3][0][4][0][0]', level=-1))
#enable_disable_boxes(gui.xanes3D_gui.xanes_analysis_gui_h.hs, 'L[0][x][3][0][4][0][0]_analysis_gridlayout', disabled=False, level=-1)

In [4]:
def determine_element(eng_list):
    print(eng_list.min(), eng_list.max())
    if ((eng_list.min()<9.669e3) & (eng_list.max()>9.669e3)):
        return 'Zn'
    elif ((eng_list.min()<8.995e3) & (eng_list.max()>8.995e3)):
        return 'Cu'
    elif ((eng_list.min()<8.353e3) & (eng_list.max()>8.353e3)):
        return 'Ni'
    elif ((eng_list.min()<7.729e3) & (eng_list.max()>7.729e3)):
        return 'Co'
    elif ((eng_list.min()<7.136e3) & (eng_list.max()>7.136e3)):
        return 'Fe'
    elif ((eng_list.min()<6.561e3) & (eng_list.max()>6.561e3)):
        return 'Mn'
    elif ((eng_list.min()<6.009e3) & (eng_list.max()>6.009e3)):
        return 'Cr'
    elif ((eng_list.min()<5.495e3) & (eng_list.max()>5.495e3)):
        return 'V'
    elif ((eng_list.min()<4.984e3) & (eng_list.max()>4.984e3)):
        return 'Ti'

def determine_fitting_energy_range(xanes_element):
    if xanes_element == 'Zn':
        xanes_analysis_edge_eng = 9.661e3
        xanes_analysis_wl_fit_eng_s = 9.664e3
        xanes_analysis_wl_fit_eng_e = 9.673e3
        xanes_analysis_pre_edge_e = 9.611e3
        xanes_analysis_post_edge_s = 9.761e3
        xanes_analysis_edge_0p5_fit_s = 9.659e3
        xanes_analysis_edge_0p5_fit_e = 9.669e3
    elif xanes_element == 'Cu':
        xanes_analysis_edge_eng = 8.989e3
        xanes_analysis_wl_fit_eng_s = 8.990e3
        xanes_analysis_wl_fit_eng_e = 9.000e3
        xanes_analysis_pre_edge_e = 8.939e3
        xanes_analysis_post_edge_s = 9.089e3
        xanes_analysis_edge_0p5_fit_s = 8.976e3
        xanes_analysis_edge_0p5_fit_e = 8.996e3
    elif xanes_element == 'Ni':
        xanes_analysis_edge_eng = 8.347e3
        xanes_analysis_wl_fit_eng_s = 8.342e3
        xanes_analysis_wl_fit_eng_e = 8.355e3
        xanes_analysis_pre_edge_e = 8.297e3
        xanes_analysis_post_edge_s = 8.447e3
        xanes_analysis_edge_0p5_fit_s = 8.340e3
        xanes_analysis_edge_0p5_fit_e = 8.352e3
    elif xanes_element == 'Co':
        xanes_analysis_edge_eng = 7.724e3
        xanes_analysis_wl_fit_eng_s = 7.725e3
        xanes_analysis_wl_fit_eng_e = 7.733e3
        xanes_analysis_pre_edge_e = 7.674e3
        xanes_analysis_post_edge_s = 7.824e3
        xanes_analysis_edge_0p5_fit_s = 7.717e3
        xanes_analysis_edge_0p5_fit_e = 7.728e3
    elif xanes_element == 'Fe':
        xanes_analysis_edge_eng = 7.126e3
        xanes_analysis_wl_fit_eng_s = 7.128e3
        xanes_analysis_wl_fit_eng_e = 7.144e3
        xanes_analysis_pre_edge_e = 7.076e3
        xanes_analysis_post_edge_s = 7.226e3
        xanes_analysis_edge_0p5_fit_s = 7.116e3
        xanes_analysis_edge_0p5_fit_e = 7.134e3
    elif xanes_element == 'Mn':
        xanes_analysis_edge_eng = 6.556e3
        xanes_analysis_wl_fit_eng_s = 6.556e3
        xanes_analysis_wl_fit_eng_e = 6.565e3
        xanes_analysis_pre_edge_e = 6.506e3
        xanes_analysis_post_edge_s = 6.656e3
        xanes_analysis_edge_0p5_fit_s = 6.547e3
        xanes_analysis_edge_0p5_fit_e = 6.560e3
    elif xanes_element == 'Cr':
        xanes_analysis_edge_eng = 6.002e3
        xanes_analysis_wl_fit_eng_s = 6.005e3
        xanes_analysis_wl_fit_eng_e = 6.012e3
        xanes_analysis_pre_edge_e = 5.952e3
        xanes_analysis_post_edge_s = 6.102e3
        xanes_analysis_edge_0p5_fit_s = 5.998e3
        xanes_analysis_edge_0p5_fit_e = 6.011e3
    elif xanes_element == 'V':
        xanes_analysis_edge_eng = 5.483e3
        xanes_analysis_wl_fit_eng_s = 5.490e3
        xanes_analysis_wl_fit_eng_e = 5.499e3
        xanes_analysis_pre_edge_e = 5.433e3
        xanes_analysis_post_edge_s = 5.583e3
        xanes_analysis_edge_0p5_fit_s = 5.474e3
        xanes_analysis_edge_0p5_fit_e = 5.487e3
    elif xanes_element == 'Ti':
        xanes_analysis_edge_eng = 4.979e3
        xanes_analysis_wl_fit_eng_s = 4.981e3
        xanes_analysis_wl_fit_eng_e = 4.986e3
        xanes_analysis_pre_edge_e = 4.929e3
        xanes_analysis_post_edge_s = 5.079e3
        xanes_analysis_edge_0p5_fit_s = 4.973e3
        xanes_analysis_edge_0p5_fit_e = 4.984e3
    return (xanes_analysis_edge_eng, xanes_analysis_wl_fit_eng_s, 
            xanes_analysis_wl_fit_eng_e, xanes_analysis_pre_edge_e,
            xanes_analysis_post_edge_s, xanes_analysis_edge_0p5_fit_s,
            xanes_analysis_edge_0p5_fit_e)

def gen_external_py_script(filename, code):
    with open(filename, 'w') as f:
        for ii in range(len(code.keys())):
            f.writelines(code[ii]+'\n')

In [7]:
print(gui.xanes2D_gui.xanes_analysis_gui_h.parent_h.xanes2D_save_trial_reg_filename)
print(gui.xanes2D_gui.xanes_analysis_gui_h.fn)

/media/Disk2/data/AIJUN_LI_Proposal_304474_June28_2019/2D_trial_reg_xanes_scan2_id_24164_2020-06-19-20-47-47.h5
None


In [2]:
import os, h5py
import numpy as np
import xanes_math as xm
import xanes_analysis as xa

with h5py.File('/media/Disk2/data/AIJUN_LI_Proposal_304474_June28_2019/2D_trial_reg_xanes_scan2_id_24164_2020-06-19-20-47-47.h5', 'r+') as f:
    imgs = f['/registration_results/reg_results/registered_xanes2D'][:]
    xanes2D_analysis_eng_list = f['/processed_XANES2D/proc_parameters/eng_list'][:]
    xanes2D_analysis_edge_eng = f['/processed_XANES2D/proc_parameters/edge_eng'][()]
    xanes2D_analysis_pre_edge_e = f['/processed_XANES2D/proc_parameters/pre_edge_e'][()]
    xanes2D_analysis_post_edge_s = f['/processed_XANES2D/proc_parameters/post_edge_s'][()]
    xanes2D_analysis_edge_jump_thres = f['/processed_XANES2D/proc_parameters/edge_jump_threshold'][()]
    xanes2D_analysis_edge_offset_thres = f['/processed_XANES2D/proc_parameters/edge_offset_threshold'][()]
    xanes2D_analysis_use_mask = f['/processed_XANES2D/proc_parameters/use_mask'][()]
    xanes2D_analysis_type = f['/processed_XANES2D/proc_parameters/analysis_type'][()]
    xanes2D_analysis_data_shape = f['/processed_XANES2D/proc_parameters/data_shape'][:]
    xanes2D_analysis_edge_0p5_fit_s = f['/processed_XANES2D/proc_parameters/edge_0p5_fit_s'][()]
    xanes2D_analysis_edge_0p5_fit_e = f['/processed_XANES2D/proc_parameters/edge_0p5_fit_e'][()]
    xanes2D_analysis_wl_fit_eng_s = f['/processed_XANES2D/proc_parameters/wl_fit_eng_s'][()]
    xanes2D_analysis_wl_fit_eng_e = f['/processed_XANES2D/proc_parameters/wl_fit_eng_e'][()]
    xanes2D_analysis_use_flt_spec = f['/processed_XANES2D/proc_parameters/flt_spec'][()]
    xanes2D_analysis_norm_fitting_order = f['/processed_XANES2D/proc_parameters/normalized_fitting_order'][()]
    xana = xa.xanes_analysis(imgs, xanes2D_analysis_eng_list, xanes2D_analysis_edge_eng, pre_ee=xanes2D_analysis_pre_edge_e, post_es=xanes2D_analysis_post_edge_s, edge_jump_threshold=xanes2D_analysis_edge_jump_thres, pre_edge_threshold=xanes2D_analysis_edge_offset_thres)


In [3]:
xana.fit_pre_edge()
xana.fit_post_edge()
xana.cal_edge_jump_map()

IndexError: tuple index out of range

In [6]:
import xanes_spectra_filters as xf
import numpy as np

In [5]:
print(xana.post_edge_fit_coef.shape)

(2, 1126, 1132)


In [14]:
eng = (np.vstack((np.vstack((np.array([xana.preset_edge_eng]), np.ones(np.array([xana.preset_edge_eng]).shape[0]))).T)
                 [:,  np.newaxis, np.newaxis, np.newaxis]))

In [12]:
(np.vstack((np.array([xana.preset_edge_eng]), np.ones(np.array([xana.preset_edge_eng]).shape[0]))).T).shape

(1, 2)

In [15]:
print(eng.shape)

(1, 1, 1, 2)
